import Head from 'next/head'
import { Container } from '../../components/Container'
import { blogPosts } from '../../lib/data';

export default function BlogPage({title, date, content}) {
  return (
    <Container>
      <Head>
      <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold mb-4">{title}</h1>
        {/* <div className='mb-4 text-sm'>{date.toString()}</div> */}
        <p className='text-xl'>{content}</p>
      </main>

    </Container>
  )
}


export async function getStaticProps(context) {
    const { params } = context
    return {
      props: blogPosts.find(item => item.slug === params.slug)
    }
}

export async function getStaticPaths() {
    return {
       paths: blogPosts.map(item => ({
           params:{
               slug: item.slug
           }
       })),
       fallback: false,
    };
  }
  
  
  