import Head from 'next/head'
import { Container } from '../components/Container'
import { about } from '../lib/data'

export default function About() {
  return (
    <Container>
      <Head>
      <title>Portfolio | About 💻</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="custom-height">
       <h1 className="text-3xl font-bold mb-4">{about.title}</h1>
        <p>{about.description}</p>
      </main>

    </Container>
  )
}
