import Head from 'next/head'
import { Container } from '../components/Container'
// import { blogPosts } from '../lib/data'
import axios from 'axios';
import { SingleBlogItem } from '../components/SingleBlogItem';

export default function Blogs({posts}) {
   
    return (
        <Container>
            <Head>
                <title>Portfolio | Blogs 💻</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className='mb-4'>
                    <h1 className="text-4xl font-bold m-6 text-center">Blogs</h1>
                    <div className="space-y-5">
                        {posts.data.map(({id, attributes}) => {
                            attributes.id = id
                            return <SingleBlogItem key={id} {...attributes} />
                        })}
                    </div>
                </div>
            </main>
        </Container>
    )
}


export async function getServerSideProps(){
    const postRes = await axios.get(`${process.env.STRAPI_URL}/posts?&sort=publishedAt:desc`);
    return {
        props: {
            posts: postRes.data
        }
    }
}


