import Head from 'next/head'

export default function About() {
    return (
        <div>
            <Head>
                <title>Portfolio | Projects 💻</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="text-5xl font-bold mb-4">Projects!</h1>
                <p className='mb-4'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor massa id neque aliquam vestibulum morbi blandit. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nam aliquam sem et tortor consequat id porta nibh venenatis. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Arcu risus quis varius quam quisque id diam vel quam. Magna ac placerat vestibulum lectus mauris. Cursus vitae congue mauris rhoncus aenean vel. Sit amet venenatis urna cursus eget nunc scelerisque. Nunc id cursus metus aliquam eleifend mi in. Eros donec ac odio tempor. Congue nisi vitae suscipit tellus mauris a diam. Diam phasellus vestibulum lorem sed risus. Et leo duis ut diam quam nulla porttitor massa id. Tristique et egestas quis ipsum suspendisse ultrices gravida. Ac ut consequat semper viverra. Quam pellentesque nec nam aliquam sem et tortor.
                </p>

                <p>
                Tortor aliquam nulla facilisi cras fermentum odio eu. Semper auctor neque vitae tempus quam pellentesque nec. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Ullamcorper eget nulla facilisi etiam dignissim diam. Quis ipsum suspendisse ultrices gravida dictum fusce. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Sed arcu non odio euismod lacinia at quis risus sed. Duis at consectetur lorem donec massa sapien faucibus. Consectetur a erat nam at lectus urna duis convallis. Eu feugiat pretium nibh ipsum consequat. Aliquam id diam maecenas ultricies. Erat pellentesque adipiscing commodo elit at imperdiet dui. Enim ut tellus elementum sagittis vitae et. Sed risus ultricies tristique nulla aliquet enim tortor. Ac placerat vestibulum lectus mauris ultrices eros in. Amet risus nullam eget felis eget nunc lobortis mattis. Sollicitudin ac orci phasellus egestas tellus. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Odio ut sem nulla pharetra diam sit amet.
                </p>
            </main>

        </div>
    )
}
