/* eslint-disable react/jsx-no-target-blank */

import Head from "next/head";
import { Container } from "../components/Container";

export default function Resume() {
    return (
        <Container>
            <Head>
                <title>Portfolio | Resume 💻</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="mb-10">
                    <div className="p-4 cv-wrapper">
                        <object type="application/pdf" data="/cv.pdf"
                        width="800px"
                        height="700px"
                        ></object>
                    </div>
                </div>
            </main>
        </Container>
    );
}